# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Mahmoud Mokhiamar
first_name: Mahmoud
middle_name: O.
last_name: Mokhiamar
contact_note: >
  Best way to reach me: email or LinkedIn.
description: > 
  Data Scientist and AI Researcher. Passionate about Deep Learning, NLP, and Real-Time Systems.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted on <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: data science, machine learning, deep learning, AI, research, computer science
lang: en
icon: ⚛️

url: https://mahmoudmokhiamar.github.io
baseurl: 
last_updated: true
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------

rss_icon: false

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true

max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false

# -----------------------------------------------------------------------------
# Analytics
# -----------------------------------------------------------------------------

google_analytics: # (optional if you want later)
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: 
blog_description: 
permalink: /blog/:year/:title/

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

newsletter:
  enabled: false

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  books:
    output: true
  news:
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Scholar (publications page)
# -----------------------------------------------------------------------------

scholar:
  last_name: [Mokhiamar]
  first_name: [Mahmoud, M.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

enable_publication_thumbnails: true
enable_publication_badges:
  altmetric: true
  dimensions: true
  google_scholar: true
  inspirehep: false

# -----------------------------------------------------------------------------
# Other site options
# -----------------------------------------------------------------------------

enable_masonry: true
enable_math: true
enable_darkmode: true
enable_medium_zoom: true
enable_progressbar: true

lazy_loading_images: true

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jemoji

# -----------------------------------------------------------------------------
# Minification and Performance
# -----------------------------------------------------------------------------

sass:
  style: compressed

jekyll-minifier:
  compress_javascript: false